// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOKFiZbihBORm9TSmS89a55g2pwhcDQU',
    appId: '1:737042604874:web:43f10437eea2eb2224d7b3',
    messagingSenderId: '737042604874',
    projectId: 'lab10-664c8',
    authDomain: 'lab10-664c8.firebaseapp.com',
    storageBucket: 'lab10-664c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyPyrPxsRx62FQeT-68HTXcHEOVlij95U',
    appId: '1:737042604874:android:987866078165dde524d7b3',
    messagingSenderId: '737042604874',
    projectId: 'lab10-664c8',
    storageBucket: 'lab10-664c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7wZR_O0r7ngGjfqNq3RgST5m8ii-_uEU',
    appId: '1:737042604874:ios:fa82af6a5d50d96b24d7b3',
    messagingSenderId: '737042604874',
    projectId: 'lab10-664c8',
    storageBucket: 'lab10-664c8.appspot.com',
    iosClientId: '737042604874-tuc6ivf8t7s0j1262kms9nkq55u39mt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7wZR_O0r7ngGjfqNq3RgST5m8ii-_uEU',
    appId: '1:737042604874:ios:fa82af6a5d50d96b24d7b3',
    messagingSenderId: '737042604874',
    projectId: 'lab10-664c8',
    storageBucket: 'lab10-664c8.appspot.com',
    iosClientId: '737042604874-tuc6ivf8t7s0j1262kms9nkq55u39mt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab10',
  );
}
